project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: GeneticStudio
      - href: documents.qmd
        text: Documents
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



